---
apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "pvc-migrate-base"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "pvc-migrate-base"
  spec:
    failedBuildsHistoryLimit: 1
    successfulBuildsHistoryLimit: 2
    runPolicy: Serial
    source:
      type: Git
      git:
        ref: "pvc-migrate-base"
        uri: "https://github.com/BCDevOps/StorageMigration.git"
      contextDir: "docker"
    strategy:
      dockerStrategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "pvc-migrate-base:latest"
